# Generated by Django 5.0.1 on 2024-04-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mental_Health', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
